server:
  port:8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/car_service
    username: postgres
    password: Str0ngP@ssword
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 10
      maximumPoolSize: 15
      idleTimeout: 80000
      maxLifetime: 2000000
      connectionTimeout: 80000
      testQuery: SELECT 1
  cloud:
    consul:
      enabled: false
